config/routes.rb
Finance::Application.routes.draw do
  resources :exchange_details

  resources :exchanges

  resources :stocks

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  belongs_to :stock
  has_many :exchange_details
  class << self
     def record(hash,stock)
        exchange = self.find_or_initialize_by_stock_id_and_sdate stock.id,hash["sdate"]
        exchange.high = hash["high"]
        exchange.low = hash["low"]
        exchange.opening = hash["opening"]
        exchange.yestoday_close = hash["yestoday_close"]
        exchange.save
     end
  end
end

app/models/exchange_detail.rb
class ExchangeDetail < ActiveRecord::Base
  belongs_to :exchange
  class << self
  def record(hash,stock)
    record = self.find_or_initialize_by_stock_id_and_stime stock.id,hash["stock_at"]
    record.update_attributes({"current_price"=>hash["current_price"],"sdate"=>hash["sdate"]})
  end

  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :exchanges
  
  def full_code
    kind+code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exchange_details_controller.rb
class ExchangeDetailsController < ApplicationController
  # GET /exchange_details
  # GET /exchange_details.xml
  def index
    @exchange_details = ExchangeDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @exchange_details }
    end
  end

  # GET /exchange_details/1
  # GET /exchange_details/1.xml
  def show
    @exchange_detail = ExchangeDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @exchange_detail }
    end
  end

  # GET /exchange_details/new
  # GET /exchange_details/new.xml
  def new
    @exchange_detail = ExchangeDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @exchange_detail }
    end
  end

  # GET /exchange_details/1/edit
  def edit
    @exchange_detail = ExchangeDetail.find(params[:id])
  end

  # POST /exchange_details
  # POST /exchange_details.xml
  def create
    @exchange_detail = ExchangeDetail.new(params[:exchange_detail])

    respond_to do |format|
      if @exchange_detail.save
        format.html { redirect_to(@exchange_detail, :notice => 'Exchange detail was successfully created.') }
        format.xml  { render :xml => @exchange_detail, :status => :created, :location => @exchange_detail }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @exchange_detail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /exchange_details/1
  # PUT /exchange_details/1.xml
  def update
    @exchange_detail = ExchangeDetail.find(params[:id])

    respond_to do |format|
      if @exchange_detail.update_attributes(params[:exchange_detail])
        format.html { redirect_to(@exchange_detail, :notice => 'Exchange detail was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @exchange_detail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /exchange_details/1
  # DELETE /exchange_details/1.xml
  def destroy
    @exchange_detail = ExchangeDetail.find(params[:id])
    @exchange_detail.destroy

    respond_to do |format|
      format.html { redirect_to(exchange_details_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  # GET /exchanges
  # GET /exchanges.xml
  def index
    @exchanges = Exchange.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @exchanges }
    end
  end

  # GET /exchanges/1
  # GET /exchanges/1.xml
  def show
    @exchange = Exchange.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @exchange }
    end
  end

  # GET /exchanges/new
  # GET /exchanges/new.xml
  def new
    @exchange = Exchange.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @exchange }
    end
  end

  # GET /exchanges/1/edit
  def edit
    @exchange = Exchange.find(params[:id])
  end

  # POST /exchanges
  # POST /exchanges.xml
  def create
    @exchange = Exchange.new(params[:exchange])

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to(@exchange, :notice => 'Exchange was successfully created.') }
        format.xml  { render :xml => @exchange, :status => :created, :location => @exchange }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @exchange.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /exchanges/1
  # PUT /exchanges/1.xml
  def update
    @exchange = Exchange.find(params[:id])

    respond_to do |format|
      if @exchange.update_attributes(params[:exchange])
        format.html { redirect_to(@exchange, :notice => 'Exchange was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @exchange.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1
  # DELETE /exchanges/1.xml
  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy

    respond_to do |format|
      format.html { redirect_to(exchanges_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # GET /stocks
  # GET /stocks.xml
  def index
    @stocks = Stock.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stocks }
    end
  end

  # GET /stocks/1
  # GET /stocks/1.xml
  def show
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.xml
  def new
    @stock = Stock.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stock }
    end
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(params[:id])
  end

  # POST /stocks
  # POST /stocks.xml
  def create
    @stock = Stock.new(params[:stock])

    respond_to do |format|
      if @stock.save
        format.html { redirect_to(@stock, :notice => 'Stock was successfully created.') }
        format.xml  { render :xml => @stock, :status => :created, :location => @stock }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.xml
  def update
    @stock = Stock.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to(@stock, :notice => 'Stock was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.xml
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to(stocks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchange_details_helper.rb
module ExchangeDetailsHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/exchange_details/_form.html.erb
<%= form_for(@exchange_detail) do |f| %>
  <% if @exchange_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange_detail.errors.count, "error") %> prohibited this exchange_detail from being saved:</h2>

      <ul>
      <% @exchange_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stock_id %><br />
    <%= f.text_field :stock_id %>
  </div>
  <div class="field">
    <%= f.label :sdate %><br />
    <%= f.date_select :sdate %>
  </div>
  <div class="field">
    <%= f.label :current_price %><br />
    <%= f.text_field :current_price %>
  </div>
  <div class="field">
    <%= f.label :hour %><br />
    <%= f.text_field :hour %>
  </div>
  <div class="field">
    <%= f.label :minutes %><br />
    <%= f.text_field :minutes %>
  </div>
  <div class="field">
    <%= f.label :stime %><br />
    <%= f.date_select :stime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exchange_details/edit.html.erb
<h1>Editing exchange_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @exchange_detail %> |
<%= link_to 'Back', exchange_details_path %>

app/views/exchange_details/index.html.erb
<h1>Listing exchange_details</h1>

<table>
  <tr>
    <th>Stock</th>
    <th>Sdate</th>
    <th>Current price</th>
    <th>Hour</th>
    <th>Minutes</th>
    <th>Stime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exchange_details.each do |exchange_detail| %>
  <tr>
    <td><%= exchange_detail.stock_id %></td>
    <td><%= exchange_detail.sdate %></td>
    <td><%= exchange_detail.current_price %></td>
    <td><%= exchange_detail.hour %></td>
    <td><%= exchange_detail.minutes %></td>
    <td><%= exchange_detail.stime %></td>
    <td><%= link_to 'Show', exchange_detail %></td>
    <td><%= link_to 'Edit', edit_exchange_detail_path(exchange_detail) %></td>
    <td><%= link_to 'Destroy', exchange_detail, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exchange detail', new_exchange_detail_path %>

app/views/exchange_details/new.html.erb
<h1>New exchange_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', exchange_details_path %>

app/views/exchange_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stock:</b>
  <%= @exchange_detail.stock_id %>
</p>

<p>
  <b>Sdate:</b>
  <%= @exchange_detail.sdate %>
</p>

<p>
  <b>Current price:</b>
  <%= @exchange_detail.current_price %>
</p>

<p>
  <b>Hour:</b>
  <%= @exchange_detail.hour %>
</p>

<p>
  <b>Minutes:</b>
  <%= @exchange_detail.minutes %>
</p>

<p>
  <b>Stime:</b>
  <%= @exchange_detail.stime %>
</p>


<%= link_to 'Edit', edit_exchange_detail_path(@exchange_detail) %> |
<%= link_to 'Back', exchange_details_path %>

app/views/exchanges/_form.html.erb
<%= form_for(@exchange) do |f| %>
  <% if @exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
      <% @exchange.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stock_id %><br />
    <%= f.text_field :stock_id %>
  </div>
  <div class="field">
    <%= f.label :sdate %><br />
    <%= f.date_select :sdate %>
  </div>
  <div class="field">
    <%= f.label :opening %><br />
    <%= f.text_field :opening %>
  </div>
  <div class="field">
    <%= f.label :close %><br />
    <%= f.text_field :close %>
  </div>
  <div class="field">
    <%= f.label :yestoday_close %><br />
    <%= f.text_field :yestoday_close %>
  </div>
  <div class="field">
    <%= f.label :high %><br />
    <%= f.text_field :high %>
  </div>
  <div class="field">
    <%= f.label :low %><br />
    <%= f.text_field :low %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing exchange</h1>

<%= render 'form' %>

<%= link_to 'Show', @exchange %> |
<%= link_to 'Back', exchanges_path %>

app/views/exchanges/index.html.erb
<h1>Listing exchanges</h1>

<table>
  <tr>
    <th>Stock</th>
    <th>Sdate</th>
    <th>Opening</th>
    <th>Close</th>
    <th>Yestoday close</th>
    <th>High</th>
    <th>Low</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exchanges.each do |exchange| %>
  <tr>
    <td><%= exchange.stock_id %></td>
    <td><%= exchange.sdate %></td>
    <td><%= exchange.opening %></td>
    <td><%= exchange.close %></td>
    <td><%= exchange.yestoday_close %></td>
    <td><%= exchange.high %></td>
    <td><%= exchange.low %></td>
    <td><%= link_to 'Show', exchange %></td>
    <td><%= link_to 'Edit', edit_exchange_path(exchange) %></td>
    <td><%= link_to 'Destroy', exchange, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exchange', new_exchange_path %>

app/views/exchanges/new.html.erb
<h1>New exchange</h1>

<%= render 'form' %>

<%= link_to 'Back', exchanges_path %>

app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stock:</b>
  <%= @exchange.stock_id %>
</p>

<p>
  <b>Sdate:</b>
  <%= @exchange.sdate %>
</p>

<p>
  <b>Opening:</b>
  <%= @exchange.opening %>
</p>

<p>
  <b>Close:</b>
  <%= @exchange.close %>
</p>

<p>
  <b>Yestoday close:</b>
  <%= @exchange.yestoday_close %>
</p>

<p>
  <b>High:</b>
  <%= @exchange.high %>
</p>

<p>
  <b>Low:</b>
  <%= @exchange.low %>
</p>


<%= link_to 'Edit', edit_exchange_path(@exchange) %> |
<%= link_to 'Back', exchanges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finance</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Kind</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stocks.each do |stock| %>
  <tr>
    <td><%= stock.code %></td>
    <td><%= stock.name %></td>
    <td><%= stock.kind %></td>
    <td><%= stock.status %></td>
    <td><%= link_to 'Show', stock %></td>
    <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
    <td><%= link_to 'Destroy', stock, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @stock.code %>
</p>

<p>
  <b>Name:</b>
  <%= @stock.name %>
</p>

<p>
  <b>Kind:</b>
  <%= @stock.kind %>
</p>

<p>
  <b>Status:</b>
  <%= @stock.status %>
</p>


<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>